<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Restore business UNIQUE keys and clean up duplicates generated by INSERT IGNORE imports.
 *
 * This migration can be heavy on large datasets. Prefer running during a maintenance window.
 */
final class Version20260527170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Dedupe controles/factures by business id and add UNIQUE indexes for safe UPSERT imports.';
    }

    public function up(Schema $schema): void
    {
        // 1) Dedupe by keeping the latest exported row for each business identifier.
        // MySQL 8 required (window functions).
        $this->addSql(<<<'SQL'
DELETE c
FROM controles c
JOIN (
  SELECT id
  FROM (
    SELECT
      id,
      ROW_NUMBER() OVER (PARTITION BY idcontrole ORDER BY date_export DESC, id DESC) AS rn
    FROM controles
  ) x
  WHERE x.rn > 1
) d ON d.id = c.id
SQL);

        $this->addSql(<<<'SQL'
DELETE f
FROM factures f
JOIN (
  SELECT id
  FROM (
    SELECT
      id,
      ROW_NUMBER() OVER (PARTITION BY idfacture ORDER BY date_export DESC, id DESC) AS rn
    FROM factures
  ) x
  WHERE x.rn > 1
) d ON d.id = f.id
SQL);

        // 2) Enforce business uniqueness for correct upserts.
        // (Previous migrations dropped those uniques; they are required for ON DUPLICATE KEY UPDATE.)
        $this->addSql('CREATE UNIQUE INDEX uq_controles_idcontrole ON controles (idcontrole)');
        $this->addSql('CREATE UNIQUE INDEX uq_factures_idfacture ON factures (idfacture)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX uq_controles_idcontrole ON controles');
        $this->addSql('DROP INDEX uq_factures_idfacture ON factures');
    }
}

